### ISSUE TITLE
get_large_files.py can not connect to hypocenter.usc.edu

### ISSUE THREAD

**Issue by mfsteve** [SCECcode/UCVMC#112]
`Retrieving files from: http://hypocenter.usc.edu/research/ucvmc/V19_4
Installing files in: /root/software/UCVMC/largefiles
Retrieving:  proj-5.0.0.tar.gz
Exception retrieving and saving largefile: <class 'urllib2.URLError'>
Error downloading (http://hypocenter.usc.edu/research/ucvmc/V19_4/lib/proj-5.0.0.tar.gz), or writing file (./proj-5.0.0.tar.gz)
Retrieving:  cvms5.tar.gz
Exception retrieving and saving largefile: <class 'urllib2.URLError'>
Error downloading (http://hypocenter.usc.edu/research/ucvmc/V19_4/model/cvms5.tar.gz), or writing file (./cvms5.tar.gz)
Retrieving:  ucvm.e
Exception retrieving and saving largefile: <class 'urllib2.URLError'>
Error downloading (http://hypocenter.usc.edu/research/ucvmc/V19_4/etree/ucvm.e), or writing file (./ucvm.e)
Retrieving:  test-grid-lib-1d.ref
Exception retrieving and saving largefile: <class 'urllib2.URLError'>
Error downloading (http://hypocenter.usc.edu/research/ucvmc/V19_4/ref/test-grid-lib-1d.ref), or writing file (./test-grid-lib-1d.ref)
Completed all required downloads to build the UCVMC programs.
`

I can't resolve hypocenter.usc.edu from any of the DNS servers I've tried.

**Comment by meihuisu** [comment]
Hi,

  It looks like hypocenter is not reachable at this moment. we will try to resolve as soon as possible.
thanks

Mei
________________________________

**Comment by mfsteve** [comment]
Working now.
