### ISSUE TITLE
simplify ucvm_query -h

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#23]
The ucvm_query -h returns unused values. Simplify it to provide more limited options including:

Usage: ucvm_query [-m models] [-c coordtype] [-f config] [-z zmin,zmax] < file.in

Flags:
	-h This help message.
	-m Comma delimited list of crustal/GTL models to query in order
	   of preference.
	-c Z coordinate mode: geo-depth (gd, default), geo-elev (ge).
	-f Configuration file. Default is ./ucvm.conf.
	-v Display model version information only.
	-z Optional depth range for gtl/crust interpolation.

**Comment by meihuisu** [comment]
done..
