### ISSUE TITLE
depth query for cvm-s4.26 extends beyond model

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#40]
The return from a cvms5 query at depth 100km, deeper than the model is defined, returns values flagged as cvms5. cencal does not return values this deep. Check on why cvms5 does.

-bash-4.2$ ./bin/ucvm_query -f ./conf/ucvm.conf -m cvms5,cvms < input_file_name.txt
Using Geo Depth coordinates as default mode.
 -117.0000    34.0000      0.000   1043.367    748.000      cvms5   3697.030   2012.850   2345.347       none      0.000      0.000      0.000      crust   3697.030   2012.850   2345.347
 -117.0000    34.0000    100.000   1043.367    748.000      cvms5   3622.903   1948.826   2336.640       none      0.000      0.000      0.000      crust   3622.903   1948.826   2336.640
 -117.0000    34.0000   1000.000   1043.367    748.000      cvms5   3560.579   1893.624   2328.927       none      0.000      0.000      0.000      crust   3560.579   1893.624   2328.927
 -117.0000    34.0000 100000.000   1043.367    748.000      cvms5   7519.175   4299.575   3127.594       none      0.000      0.000      0.000      crust   7519.175   4299.575   3127.594

**Comment by meihuisu** [comment]
rerunning it:

./bin/ucvm_query -f ./conf/ucvm.conf -m cvms5,cvms < input_file_name.txt

Using Geo Depth coordinates as default mode.
 -117.0000    34.0000      0.000   1041.749    710.100      cvms5   3550.244   1894.445   2329.044       none      0.000      0.000      0.000      crust   3550.244   1894.445   2329.044
 -117.0000    34.0000    100.000   1041.749    710.100      cvms5   3494.419   1847.536   2322.278       none      0.000      0.000      0.000      crust   3494.419   1847.536   2322.278
 -117.0000    34.0000   1000.000   1041.749    710.100      cvms5   3505.819   1858.691   2323.908       none      0.000      0.000      0.000      crust   3505.819   1858.691   2323.908
 -117.0000    34.0000 100000.000   1041.749    710.100       cvms   8086.907   4727.903   3141.923       none      0.000      0.000      0.000      crust   8086.907   4727.903   3141.923

and,
./ucvm_query -f ../conf/ucvm.conf -m cvms5 < input_file_name.txt
Using Geo Depth coordinates as default mode.
 -117.0000    34.0000      0.000   1041.749    710.100      cvms5   3550.244   1894.445   2329.044       none      0.000      0.000      0.000      crust   3550.244   1894.445   2329.044
 -117.0000    34.0000    100.000   1041.749    710.100      cvms5   3494.419   1847.536   2322.278       none      0.000      0.000      0.000      crust   3494.419   1847.536   2322.278
 -117.0000    34.0000   1000.000   1041.749    710.100      cvms5   3505.819   1858.691   2323.908       none      0.000      0.000      0.000      crust   3505.819   1858.691   2323.908
 -117.0000    34.0000 100000.000   1041.749    710.100       none      0.000      0.000      0.000       none      0.000      0.000      0.000       none      0.000      0.000      0.000

and,
./ucvm_query -f ../conf/ucvm.conf -m cvms < input_file_name.txt
Using Geo Depth coordinates as default mode.
 -117.0000    34.0000      0.000   1041.749    710.100       cvms   4886.639   2659.200   2636.600       none      0.000      0.000      0.000      crust   4886.639   2659.200   2636.600
 -117.0000    34.0000    100.000   1041.749    710.100       cvms   4886.639   2659.200   2636.600       none      0.000      0.000      0.000      crust   4886.639   2659.200   2636.600
 -117.0000    34.0000   1000.000   1041.749    710.100       cvms   4886.694   2659.225   2636.609       none      0.000      0.000      0.000      crust   4886.694   2659.225   2636.609
 -117.0000    34.0000 100000.000   1041.749    710.100       cvms   8086.907   4727.903   3141.923       none      0.000      0.000      0.000      crust   8086.907   4727.903   3141.923
