### ISSUE TITLE
invalid model listed in plot_z25_map.py

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#43]
Trying to reproduce the z25 map on wiki at:
https://scec.usc.edu/scecpedia/Study_17.3_Data_Products#Velocity_Maps

using the plot_z25_map.py script, it presents user with choice of cvms, but the names are incosistent. No cvmsi is listed. cvm4 is listed, cvms4.26 is listed. giving cvms4 as model throws an exception. Determine where this script gets its list of models and determine why it does not include cvmsi, and why it presents a choice of invalid models.

**Comment by meihuisu** [comment]
from common.py
## Known CVMs that can be installed with UCVM.
UCVM_CVMS = {"1d":"1D", \
             "1dgtl":"1D w/ Vs30 GTL", \
             "bbp1d":"Broadband Northridge Region 1D Model", \
             "cvms":"CVM-S4", \
             "cvms5":"CVM-S4.26", \
             "cvmsi":"CVM-S4.26.M01", \
             "cca":"CCA 06", \
             "cs173":"CyperShake 17.3", \
             "cs173h":"CyperShake 17.3 with San Joaquin and Santa Maria Basins data", \
             "cvmh":"CVM-H 15.1.1", \
             "cencal":"USGS Bay Area Model"}

**Comment by meihuisu** [comment]
the script uses the install/model's directory name as the string index into this 
structure above:: so, had to make them match up.


From which CVM would you like this data to come:
	1) CyperShake 17.3 with San Joaquin and Santa Maria Basins data(cs173h)
	2) USGS Bay Area Model(cencal)
	3) CVM-H 15.1.1(cvmh)
	4) CCA 06(cca)
	5) CVM-S4.26.M01(cvmsi)
	6) CVM-S4(cvms)
	7) CVM-S4.26(cvms5)
	8) 1D(1d)
