### ISSUE TITLE
basin_query_mpi features

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#46]
Basin_query_mpi returns only one basin depth value. Give user an option which  value is returned, first occurence, second, or both. Also give user option of the output format with basin_query_mpi default to binary,

**Comment by meihuisu** [comment]
Another common approach now a day is a json blob of meta data

and data. the meta data would have description about the data and

give hints of how to process the subsequent data and these all

reside in one single output file. json blob is easily processed with

python, javascript and R and other data processing language as

part of standard builtin support.

________________________________
