### ISSUE TITLE
Seg fault when models loaded in certain orders

### ISSUE THREAD

**Issue by scallag** [SCECcode/UCVMC#47]
In trying to create a large velocity mesh, I ran into a segmentation fault in UCVM.  Specifically, the seg fault was getting thrown around line 350 of cvmsi.c:

q_vp[z][y][x] = cvmsi_buf[offset].vp;

The proximal cause of the seg fault is that _offset_ was negative.  Tracking the code back through, _offset_ was negative because some of the longitudes passed into the cvmsi_query() function in cvmsi.c were nonsensical, <-180 or >180.  This is because the array used to store the longitudes was being overwritten.

Eventually I discovered that the cause of the problem is a redeclaration of the variable _dataBuffer_.  In ucvm_model_cvmsi.c, the variable _dataBuffer_ is declared in line 22:

cvmsi_data_t *dataBuffer = NULL;

and is allocated as part of the model initialization in the ucvm_cvmsi_model_init() function, to CVMSI_MAX_POINTS * sizeof(cvmsi_data_t).  However, a variable with the same name is also declared in ucvm_model_plugin.c, line 35:

basic_properties_t *dataBuffer;

and is allocated as part of the initialization there, in ucvm_plugin_model_init(), to MODEL_POINT_BUFFER * sizeof(basic_properties_t).

Most of the time this redeclaration doesn't actually cause an issue.  If only one of the init functions is never called, then the variable is never reallocated.  Since at this point the only model which uses the plugin code is CCA, both CCA and CVM-S4.26 must be loaded.  Additionally, the allocation done in ucvm_cvmsi_model_init() is much larger than the allocation in ucvm_plugin_model_init().  So if the CCA model is loaded first, then CVM-S4.26, _dataBuffer_ is changed from pointing to a small buffer to a large one.  Since both init functions are called before any data is written, having a too-large buffer doesn't cause any issues for CCA, and it's the right size for CVM-S4.26.

However, if CVM-S4.26 is initialized before a plugin model, such as CCA, then _dataBuffer_ is changed to point to a small buffer which is much smaller than what CVM-S4.26 expects.  Then, when CVM-S4.26 tries to use it, the array is overrun and the memory used for tracking the longitudes eventually gets clobbered.

The easiest fix is to rename one of the variables.  Ideally we would also turn on a compiler flag to warn us of a variable redefinition, in case there are other variables which share names.

**Comment by meihuisu** [comment]
I have patched the code, can you give me the example you used that caused the segfault?
