### ISSUE TITLE
Configure failed on Blue Waters

### ISSUE THREAD

**Issue by hzfmer** [SCECcode/UCVMC#48]
I failed to install UCVMC on Blue Waters. The error message is:

*****************************************
**(I used absolute path when configuring, but changed it to ../../ucvm-17.1.0 here for privacy.)**
...
Installing UCVM software...

Running aclocal

Running automake

Running autoconf

Running ./configure for UCVM

...

checking for etree_open in -letree... no
configure: error: "**Etree library not found; use --with-etree-lib-path**"

ERROR:
An error occurred while trying to setup UCVM. Specifically, the error was:

Error executing command.

At step: [./configure --with-etree-include-path=../../ucvm-17.1.0/lib/euclid3/include --with-etree-lib-path=../../ucvm-17.1.0/lib/euclid3/lib --with-proj4-include-path=../../ucvm-17.1.0/lib/proj-4/include --with-proj4-lib-path=../../ucvm-17.1.0/lib/proj-4/lib --with-fftw-include-path=../../ucvm-17.1.0/lib/fftw/include --with-fftw-lib-path=../../ucvm-17.1.0/lib/fftw/lib --enable-model-cvms --with-cvms-include-path=../../ucvm-17.1.0/model/cvms/include --with-cvms-lib-path=../../ucvm-17.1.0/model/cvms/lib --with-cvms-model-path=../../ucvm-17.1.0/model/cvms/src --enable-model-cvms5 --with-cvms5-lib-path=../../ucvm-17.1.0/model/cvms5/lib --with-cvms5-include-path=../../ucvm-17.1.0/model/cvms5/include --enable-model-cvmsi --with-cvmsi-lib-path=../../ucvm-17.1.0/model/cvms426/lib --with-cvmsi-include-path=../../ucvm-17.1.0/model/cvms426/include --with-cvmsi-model-path=../../ucvm-17.1.0/model/cvms426/model/i26 --enable-model-cvmh --with-cvmh-include-path=../../ucvm-17.1.0/model/cvmh1510/include --with-cvmh-lib-path=../../ucvm-17.1.0/model/cvmh1510/lib --with-gctpc-lib-path=../../ucvm-17.1.0/model/cvmh1510/lib --with-cvmh-model-path=../../ucvm-17.1.0/model/cvmh1510/model --enable-model-cencal --with-cencal-lib-path=../../ucvm-17.1.0/model/cencal/lib --with-cencal-include-path=../../ucvm-17.1.0/model/cencal/include/cencalvm/query/ --with-cencal-model-path=../../ucvm-17.1.0/model/cencal/model/USGSBayAreaVM-08.3.0.etree --with-cencal-extmodel-path=../../ucvm-17.1.0/model/cencal/model/USGSBayAreaVMExt-08.3.0.etree --prefix=../../ucvm-17.1.0
]

******************************************

More details in config.log shows:

****************
configure:5055: cc -c -I../../ucvm-17.1.0/lib/euclid3/include -Wall -O3 -D_LA    RGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -g -O2  conftest.c >&5
237 CC-2119 craycc: ERROR in command line
238   The phase argument or the comma before the phase argument is missing for the -W option.
239 configure:5062: $? = 1
(and a bunch of similar ERRORs for other .h files
)
****************

[config.log](https://github.com/SCECcode/UCVMC/files/1769136/config.log)

I checked that the libraries are there, in the correct directory. Why the configuration failed? 
Any comments are appreciated!

**Comment by meihuisu** [comment]
Hi,


  Did you


module unload PrgEnv-cray
module load PrgEnv-gnu


  before starting the build ?


  your config.log is showing..



configure:3207: checking for C compiler version
configure:3215: cc --version >&5
CC-2115 craycc: ERROR in command line
  "--version" is an invalid command-line option.
CC-2107 craycc: ERROR in command line
  No valid filenames are specified on the command line.
configure:3219: $? = 1





mei




________________________________

**Comment by hzfmer** [comment]
It works! Thanks a lot!

I didn't realize I had not load PrgEnv-gnu. Perhaps the installation guide should add the command to switch module first..
