### ISSUE TITLE
Results from tiled models in wrong location

### ISSUE THREAD

**Issue by scallag** [SCECcode/UCVMC#49]
With certain combinations of tiled models for certain regions, results from one model are moved to another.  For example, when using the model combination cencal,cca,cvms426 for a large CyberShake region, the point (-125, 40, 0.0) is first set in cencal, but is then reset in cca, which is incorrect.

The cause of this bug is in ucvm_model_plugin.c .  The query code works by assembling all points which have not already been populated into the pointsBuffer.  Then the query is run, and the results are copied back into the data array which was passed into the query function, in lines 246-251.  However, this copy-back code assumes that the points which were queried were contiguous in the data array.  This is not necessarily the case, and if it's not, then points which were already populated by a higher-priority model might be overwritten.

The same bug exists in at least ucvm_model_cvmsi.c , lines 177-180, and may exist in other models as well.

I implemented a fix for cvmsi in 2016, which is to keep track of the mapping between the index in the full data array and the index in the query buffer.  In ucvm_model_cvmsi.c, I added the following at line 151:

  int* index_mapping = malloc(sizeof(int)*CVMSI_MAX_POINTS);
  if (index_mapping==NULL) {
        fprintf(stderr, "Memory allocation of index_mapping failed, aborting.\n");
        exit(1);
  }

Then, I changed lines 177-180 to:
                                  data[index_mapping[j]].crust.source = ucvm_cvmsi_id;
                                  data[index_mapping[j]].crust.vp = dataBuffer[j].prop.vp;
                                  data[index_mapping[j]].crust.vs = dataBuffer[j].prop.vs;
                                  data[index_mapping[j]].crust.rho = dataBuffer[j].prop.rho;

and lines 202-205 to:
            data[index_mapping[j2]].crust.source = ucvm_cvmsi_id;
            data[index_mapping[j2]].crust.vp = dataBuffer[j2].prop.vp;
            data[index_mapping[j2]].crust.vs = dataBuffer[j2].prop.vs;
            data[index_mapping[j2]].crust.rho = dataBuffer[j2].prop.rho;

A similar approach works with ucvm_model_plugin.c to fix the issue.

**Comment by meihuisu** [comment]
patched ucvm_model_plugin.c and ucvm_model_cvmsi.c
