### ISSUE TITLE
"ADIOI_CRAY_WRITECONTIG" error when extracting large mesh

### ISSUE THREAD

**Issue by hzfmer** [SCECcode/UCVMC#51]
I got mulitple similar errors when extracting a large velocity mesh(2.1T) on Titan:

\* ...
ADIOI_CRAY_WRITECONTIG(261): filename='la_habra_large_cvmsi_20m.media'  error='Input/output error'  errno=5  PE=03599  W_rec=16784  off=474083277000  len=0000003000  See MPICH_MPIIO_ABORT_ON_RW_ERROR.
Error writing to file
...*

*******************************
The ***.pbs** file includes:
*
module load iobuf
aprun -n 20736 $UCVMBIN/ucvm2mesh-mpi -f ucvm_la_habra_large.conf
*

*******************************
The ***.conf** file includes:

x0=-119.288842
y0=34.120549
z0=0.0

\# Number of cells along each dim
nx=9000
ny=6750
nz=3072

\# Partitioning of grid among processors
px=18
py=18
pz=64

\# Vs/Vp minimum
vp_min=0
vs_min=0

\# Mesh and grid files, format
meshfile=la_habra_large_cvmsi_20m.media
gridfile=la_habra_large_cvmsi_20m.grid
meshtype=IJK-12

\# Location of scratch dir
scratch=/lustre/atlas/proj-shared/geo112/****/cvm

*************************************
A very similar **pbs** and **conf** file work well when extract a smaller velocity mesh (100+G):
*
nx=1400
ny=1400
nz=600
\# Partitioning of grid among processors
px=25
py=25
pz=10
*
******************************************

so I assume it is because some IO problems on Titan? Is there any suggestion to fix this issue?  

Thank you!

**Comment by meihuisu** [comment]
use ucvm2mesh_mpi_layer. This should scale better for large mesh.
