### ISSUE TITLE
UCVM_COORD_GEO_ELEV break cvmh

### ISSUE THREAD

**Issue by breuera** [SCECcode/UCVMC#52]
When setting `UCVM_PARAM_QUERY_MODE` to `UCVM_COORD_GEO_ELEV`, cvmh breaks and returns strange results.
`UCVM_COORD_GEO_DEPTH` works.

Reproducer:

```
#include <iostream>

extern "C" {
#include "ucvm.h"
}

int main() {
  if( ucvm_init( "ucvm.conf" ) != UCVM_CODE_SUCCESS ) {
    std::cerr << "failed initializing UCVM" << std::endl;
    return 1;
  };
  
  if( ucvm_add_model_list( "cvmh") != UCVM_CODE_SUCCESS ) {
    std::cerr << "failed setting model: " << "cvmh" << std::endl;
    return 1;
  }

/*
 * Breakin change, result:
 * 0
 * 0
 * 1000
 */
#if 0
  if( ucvm_setparam( UCVM_PARAM_QUERY_MODE, UCVM_COORD_GEO_ELEV ) != UCVM_CODE_SUCCESS  ) {
    std::cerr << "failed setting param query mode: " << "UCVM_COORD_GEO_ELEV" << std::endl;
    return 1;
  }
#endif

/*
 * Works, result:
 * 1600
 * 206.897
 * 1697.12
 */
#if 1
  if( ucvm_setparam( UCVM_PARAM_QUERY_MODE, UCVM_COORD_GEO_DEPTH ) != UCVM_CODE_SUCCESS  ) {
    std::cerr << "failed setting param query mode: " << "UCVM_COORD_GEO_DEPTH" << std::endl;
    return 1;
  }
#endif


  ucvm_point_t l_test;
  l_test.coord[0] = -115.576;
  l_test.coord[1] = 32.7567;
  l_test.coord[2] = 0;
  ucvm_data_t l_data;
  ucvm_query( 1, &l_test, &l_data );
  std::cout << l_data.cmb.vp << std::endl;
  std::cout << l_data.cmb.vs << std::endl;
  std::cout << l_data.cmb.rho << std::endl;
  return 0;
}
```

**Comment by meihuisu** [comment]
bad_vs.png 
<img src="https://user-images.githubusercontent.com/9042455/58139035-cdb27100-7bed-11e9-8af9-afff9ea69fca.png" width=400px height=300px>
bbad_vs.png
<img src="https://user-images.githubusercontent.com/9042455/58139040-d440e880-7bed-11e9-93e4-d822cf0785a8.png" width=400px height=300px>

bad.png 
<img src="https://user-images.githubusercontent.com/9042455/58139159-6517c400-7bee-11e9-83d0-6db0eb2d529c.png" width=500px height=500px>

That particular  point fall into a 'step' in the cvmh's boundary. You can see it if you plot the following plots:

<pre>
./plot_elevation_cross_section.py -b 32.7567,-115.852 -u 32.7567,-115.3 -h 100 -v -10  -d vs  -c cvmh -a d -s 100 -e -500 -o cvmh.png
</pre>
and 
<pre>
./plot_elevation_cross_section.py -b 32.7567,-115.852 -u 32.7567,-115.3 -h 100 -v -10 -d vs  -c cvmsi -a d -s 100 -e -500 -o cvmsi.png
</pre>

and an elevation profile

<pre>
./plot_elevation_profile.py -s 32.7567,-115.576 -b 0 -e -100 -d vs,vp,density -v -1 -c cvmh -o depth.png
</pre>

and probe the models with
<pre>
ucvm_query -f ../conf/ucvm.conf -m cvmh -c ge < in
ucvm_query -f ../conf/ucvm.conf -m cvmsi -c ge < in
</pre>

and input values of,
<pre>
-115.576 32.7567 10 
-115.576 32.7567 0 
-115.576 32.7567 -6.62
-115.576 32.7567 -6.63
-115.576 32.7567 -10
-115.576 32.7567 -50 
-115.576 32.7567 -52 
-115.576 32.7567 -100 
</pre>
