### ISSUE TITLE
Python scripts do not specify version

### ISSUE THREAD

**Issue by scallag** [SCECcode/UCVMC#59]
When trying to run ./get_large_files.py on Blue Waters, I get the error:

  File "./get_large_files.py", line 20
    print "Exception retrieving and saving largefile:",e
                                                     ^
SyntaxError: Missing parentheses in call to 'print'

because Blue Waters now defaults to python3.  Changing the top line to "#!/usr/bin/env python2" would resolve the issue.

**Comment by meihuisu** [comment]
Are our python code coupled tightly with python2?


________________________________

**Comment by meihuisu** [comment]
done
