### ISSUE TITLE
How to download SCEC BBP (with out virtual box)

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#60]
As a research scholar from IIT Hyderabad, INDIA, I was using SCEC BBP since 2015 with the virtual box on my laptop. Now, we have access to high-performance computing facility in our College. I want to install BBP directly on to the server. I am unable to download SCEC BBP with the command:

"git clone https://github.com/SCECcode/bbp.git"

**Comment by meihuisu** [comment]
should be SCECcode/bbp issue.
