### ISSUE TITLE
ucvm install "make check" fails on test

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#82]
make check shows error after:
Test:UCVM Lib add model SCEC CVM-SI
PASS
./accepttest
Test: ucvm librareay 1d model w/ large grid
FAIL: assertion 225.600006 != 349.00000
FAIL: Mismatch on line 13395
./accetp_test.py /home/ucvm_user/ucvm_bin/tests
Running test test_ssh_generate
[SUCCESS]

**Comment by meihuisu** [comment]
pass now
