### ISSUE TITLE
plotting scripts fail if run outside utilities directory

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#83]
Even with pythonpath set to utilities and pycvm directory, the plot_horizontal_slice.py fails if run outside the utilities directory due to a relative path name that searches for models. Update so the plotting utils can be run from anywhere.

**Comment by meihuisu** [comment]
set UCVM_INSTALL_PATH to where UCVM is installed.  The plotting scripts should
be runnable outside of the utilities directory then.

**Comment by meihuisu** [comment]
plotting script now has -I installdir to accept install directory location
