### ISSUE TITLE
config.guess, config.sub files for proj-4 outdated for Summit

### ISSUE THREAD

**Issue by scallag** [SCECcode/UCVMC#86]
I got the following error when trying to install UCVMC, cybershake_18_8 tag on Summit:

checking build system type... ./config.guess: unable to guess system type

This script, last modified 2007-03-06, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2007-03-06

uname -m = ppc64le
uname -r = 4.14.0-49.18.1.el7a.ppc64le
uname -s = Linux
uname -v = #1 SMP Thu Nov 29 03:27:24 EST 2018

/usr/bin/uname -p = ppc64le
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = ppc64le
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 4.14.0-49.18.1.el7a.ppc64le
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Thu Nov 29 03:27:24 EST 2018
configure: error: cannot guess build type; you must specify one

ERROR:
An error occurred while trying to setup UCVM. Specifically, the error was:

Error executing command.

At step: ['./configure', u'--prefix=/gpfs/alpine/proj-shared/geo112/CyberShake/software/UCVM/ucvm-cybershake_18_8/lib/proj-4', u'--with-jni=no']

I think the issue is that the config.guess and config.sub files which ship with proj-4.8.0 are too old to correctly handle Summit's architecture.  When I copied in the config.guess and config.sub files in automake on Summit (at /usr/share/automake-1.13/), I could configure proj-4 correctly.

**Comment by meihuisu** [comment]
We are moving to pro-5 in the new release and the config.guess and config. sub are both dated : timestamp='2017-04-02', should be able to recognize SUMMIT
